version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  commands:
    - pip install cmake
    - cmake --workflow --preset documentation-workflow
    # Copy built documentation to Read the Docs output directory
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r build/* $READTHEDOCS_OUTPUT/html/
